#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell available, you may
#       want to edit this line so it runs the shell you do have.
#
#   (2) Ideally, you would put the Gradle wrapper (gradle-wrapper.jar and gradle
#       wrapper.properties) in version control.
#
#   (3) This script assumes you have Java installed
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing slash with case alternate unexpanded.
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}	# remove leading ...
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR="gradle-wrapper.jar"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != maximum.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
pw32=false
nwjs=false
darwin=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NWJS* )           nwjs=true    ;; #(
esac

CLASSPATH=$APP_HOME/gradle/wrapper/$APP_JAR


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" ; then
    case $- in  #(
      *i*) ;;
      *) arg=$( printf '%s\n' "$-" | grep -o . | tr '\n' ' ' | sed 's| ||g' ); printf '%s\n' "-nosplitargs $arg" ;;
    esac
    num_args=$( java -version 2>&1 | grep -oP 'version "?\K[\d.]+' | head -c2 )
    if [ "$num_args" -ge 9 ] ; then
        JVM_OPTS="$JVM_OPTS -XX:ActiveProcessorCount=\$(nproc)"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    JVM_OPTS="$JVM_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --path --mixed "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/bash
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        arg=$( printf '%s\n' "$arg" | sed "s/'/'\\\\''/g" ) # let's quote this up
        JVM_OPTS="$JVM_OPTS \"$arg\""
    done
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * GRADLE_OPTS, GRADLE_SYSTEM_PROPS, JAVA_OPTS, and JAVA_OPTS_APPEND are environment variables that must be referenced as is
#   * Collect all default JVM options and the appends from GRADLE_INITIAL_JVM_OPTS
#   * Then append GRADLE_OPTS and JAVA_OPTS (consulted via the backdoor of the shell eval)

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Posix shells we could instead do:
#   - the string is quoted with single or double quotes;
#   - command substitution "`" backticks and "$()" syntax;
#   - parameter expansion "$var" and "${var}" but not ${1+"$@"} until the closing ")";
#   - arithmetic expansion "$((expr))";
#
# which means that characters in the string before the close quote must
# match [^$`\], i.e. they cannot be a dollar sign, backtick or backslash.
#
# This is neither flexible nor robust; in particular it breaks on
# whitespace. That said, Posix shells will word-split by default.
eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]./:=@_]~\\&~g; ' |
        tr '\n' ' '
    ) $GRADLE_OPTS \"\$@\""

exec "$JAVACMD" "$@"
