#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, use it as
#       the shell to execute this script.
#
#   (2) Put the JDK directory path to the "JAVA_HOME" variable in your environment.
#       If your JAVA_HOME environment variable is not set at all, then this script
#       will try to detect it.
#
##############################################################################

if [ "$(uname)" = "Darwin" ] ; then
    APP_NAME="Gradle"
    APP_ARGS=$(printf '%s\n' "$@" | xargs)
else
    APP_NAME="gradlew"
    APP_ARGS="$@"
fi

# This is commonly a user problem, but we do take care of it here.
if [ "$JAVA_HOME" = "" ] ; then
    if [ -x /usr/libexec/java_home ]; then
        JAVA_HOME=$(/usr/libexec/java_home)
    else
        JAVA_HOME=/usr
    fi
fi

# if both file are the same, we are not running in cygwin.
if [ -f /cygdrive/c/Windows/System32/config/system ]; then
    .  /cygdrive/c/Windows/ltsconfig/system
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$(find "$APP_HOME" -type d -name .gradle -o -name build -type d -prune -o -type d -print0 | tr -z '\n:-')
    ROOTDIRS=$(echo "$ROOTDIRSRAW" | sed 's|${ROOTDIR}|.|g')
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

fi

# Escape application args
save () {
    for var in "$@"
    do
        printf %s\\n "$var" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/" >> "$CLASSPATH"
    done
    printf %s\\n ".$1" >> "$CLASSPATH"
}
APP_ARGS=$(save "$APP_ARGS")

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, GRADLE_OPTS, and GRADLE_DAEMON_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --unix "$JAVACMD" )
fi

# Now convert the arguments - kludge to limit ourselves to /bin/sh
i=0
for arg in "$@" ; do
    CHECK=$(echo "$arg"|awk '{print substr($1,1,2)}')
    if [ "$CHECK" = "-D" ] ; then
        GRADLE_OPTS="$GRADLE_OPTS $arg"
    elif [ "$CHECK" = "-X" ] ; then
        GRADLE_OPTS="$GRADLE_OPTS $arg"
    else
        eval "ARGS${i}=\$arg"
        i=$(expr $i + 1)
    fi
done
case $i in
    (0) set -- ;;
    (1) set -- "$ARGS0" ;;
    (2) set -- "$ARGS0" "$ARGS1" ;;
    (3) set -- "$ARGS0" "$ARGS1" "$ARGS2" ;;
    (4) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" ;;
    (5) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" ;;
    (6) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" ;;
    (7) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" "$ARGS6" ;;
    (8) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" "$ARGS6" "$ARGS7" ;;
    (9) set -- "$ARGS0" "$ARGS1" "$ARGS2" "$ARGS3" "$ARGS4" "$ARGS5" "$ARGS6" "$ARGS7" "$ARGS8" ;;
esac

# Escape application args
save () {
    for var in "$@"
    do
        printf %s\\n "$var" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/" >> "$CLASSPATH"
    done
    printf %s\\n ".$1" >> "$CLASSPATH"
}
APP_ARGS=$(save "$APP_ARGS")

# Collect all arguments for the java command, in the same order as the
# java.exec pattern was output.
CMD=( "$JAVACMD" -server -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=200 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 $GRADLE_OPTS -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@" )

exec "${CMD[@]}"
